# Generated by Django 5.1.1 on 2024-09-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_categories_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEntry',
        ),
    ]
